name: Node CI
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  print:
    runs-on: ubuntu-18.04
    steps:
      - name: print files
        run: ls
# name: Audit live site
# on:
#   pull_request:
#     branches:
#       - master
# jobs:
#   audit:
#     runs-on: ubuntu-latest
#     steps:
#       - name: check out code
#         uses: actions/checkout@v1
#       - name: Read files
#         uses: docker://dictybase/snapshot-upload:test
#         env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
# - name: Audit live URL
#   uses: docker://dictybase/lighthouse-audit:comment
#   with:
#     url: "https://eric.dictybase.dev/publication/26088819"
#   env:
#     GH_TOKEN: ${{ secrets.GH_TOKEN }}
# - name: Upload results as an artifact
#   uses: actions/upload-artifact@master
#   with:
#     name: report
#     path: "./report"
